repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        exclude: ^alembic/.*$
        language_version: python3

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^alembic/.*$
        language_version: python3

  - repo: https://github.com/PyCQA/pylint
    rev: v2.17.0
    hooks:
      - id: pylint
        exclude: ^alembic/.*$
        name: pylint (optional)
        language: system
        entry: python -m pylint --init-hook "import sys; sys.path.append('.')"
        args:
          - app
        additional_dependencies: []